import type { VisualElement as E, VisualLesson, VisualStep } from './types';

const text = (id: string, x: number, y: number, value: string, tone: E['tone'] = 'muted'): E => ({ id, kind: 'text', x, y, text: value, size: 17, tone });
const matrix = (id: string, x: number, y: number, values: (number | string)[][], label: string, tone: E['tone'] = 'blue', extra = {}): E => ({ id, kind: 'matrix', x, y, values, label, tone, cellW: 44, cellH: 34, ...extra });
const arrow = (id: string, x1: number, y1: number, x2: number, y2: number, tone: E['tone'] = 'green'): E => ({ id, kind: 'arrow', x1, y1, x2, y2, tone });
const box = (id: string, x: number, y: number, w: number, h: number, label: string, tone: E['tone'] = 'blue'): E => ({ id, kind: 'box', x, y, w, h, label, tone });
const step = (title: string, description: string, elements: E[]): VisualStep => ({ title, description, elements });
const lesson = (id: string, title: string, summary: string, note: string, steps: VisualStep[]): VisualLesson => ({ id, title, summary, note, steps });

const heads = lesson('attention-head-sharing', 'Four queries, fewer stored K/V heads', 'Watch query connections regroup while the four output heads remain separate.', 'Toy model: four query heads, one sequence and equal head widths. Panels compare trained architectures, not an inference-time conversion.', [4, 2, 1].map((count, s) => step(
  ['MHA: one pair per query', 'GQA: two queries share each pair', 'MQA: every query shares one pair'][s],
  ['Four query heads connect to four distinct key/value pairs.', 'The arrows regroup into two pairs. Query and output head counts remain four.', 'All arrows converge on one stored pair. Each query still produces its own attention result.'][s],
  [text('ql', 35, 48, 'Query heads'), text('kvl', 275, 48, 'Stored K/V pairs'), text('ol', 535, 48, 'Output heads'),
    ...Array.from({ length: 4 }, (_, i) => {
      const group = Math.floor(i / (4 / count)); const ky = 75 + group * (220 / count);
      return [box(`q${i}`, 40, 75 + i * 56, 90, 36, `Q${i}`), arrow(`a${i}`, 132, 93 + i * 56, 275, ky + 18), box(`o${i}`, 545, 75 + i * 56, 95, 36, `O${i}`, 'purple'), arrow(`b${i}`, 405, ky + 18, 540, 93 + i * 56, 'purple')];
    }).flat(), ...Array.from({ length: count }, (_, i) => box(`kv${i}`, 275, 75 + i * (220 / count), 130, 36, `K${i}  V${i}`, 'green')),
    text('size', 120, 335, `Logical KV payload: ${count}/4 of the MHA example`)]
)));

const flash = lesson('flashattention-tiles', 'One softmax row, streamed in tiles', 'Move a two-key tile through the score row and carry a shared normalization.', 'Toy unscaled scores [0,0,ln 2,ln 2], scalar values [1,3,5,7]. Numbers shown rounded. The grid is a teaching view, not a full score matrix stored in HBM.', [0, 1, 2].map(s => step(
  ['Load the first two keys', 'Shift the tile and rescale', 'Normalize once, after all keys'][s],
  ['The first tile has maximum 0, exponential sum 2 and weighted sum 4.', 'The maximum rises to ln 2. Old sums halve; the new tile adds 2 to the denominator and 12 to the numerator.', 'Divide the accumulated weighted sum 14 by denominator 3. Independently averaging tile outputs would instead give 4.'][s],
  [matrix('scores', 80, 90, [[0, 0, 'ln 2', 'ln 2']], 'Scores for one query', 'blue', { cellW: 65, highlight: s === 0 ? [[0, 0], [0, 1]] : [[0, 2], [0, 3]] }), matrix('values', 80, 185, [[1, 3, 5, 7]], 'Values', 'green', { cellW: 65 }),
    { id: 'tile', kind: 'path', d: `M ${s === 0 ? 76 : 206} 78 h 138 v 151 h -138 Z`, tone: 'amber', width: 3 },
    arrow('load', 350, 155, 435, 155), matrix('state', 445, 92, s === 0 ? [[0], [2], [4]] : [['ln 2'], [3], [14]], 'Running state', 'purple', { cellW: 90, rowLabels: ['m', 'l', 'u'] }), ...(s === 2 ? [matrix('out', 570, 220, [['4.67']], 'Output', 'green', { cellW: 70 }), arrow('normalize', 535, 185, 570, 212)] : []),
    text('calc', 80, 286, s === 0 ? 'u = 1 + 3 = 4' : 'l = ½ × 2 + 2 = 3;  u = ½ × 4 + 12 = 14'), text('result', 80, 325, s === 2 ? 'Output = 14 / 3 ≈ 4.67' : 'Keep only tile workspace + running statistics')]
)));

const rope = lesson('rope-pair-rotation', 'Position rotates a coordinate pair', 'Follow two vectors as position changes their angle and their dot product.', 'Toy single 2D pair with angular frequency π/4 per position; q=k=[1,0]. Solid blue Q and dashed green K coincide initially. Both have unit length. Real heads use many pair frequencies.', [0, 1, 2].map(s => {
  const qa = s === 2 ? Math.PI / 4 : 0; const ka = s === 0 ? 0 : s === 1 ? Math.PI / 4 : Math.PI / 2;
  return step(['Start with aligned vectors', 'Move the key one position', 'Shift both positions together'][s], ['At position zero, both unit vectors align, so their dot product is one.', 'The key turns 45 degrees while the query stays fixed; the dot product becomes about 0.707.', 'Both vectors turn another 45 degrees. Their relative angle stays 45 degrees, so the dot product stays about 0.707.'][s], [
    { id: 'unit', kind: 'circle', x: 195, y: 235, r: 105, tone: 'muted' }, arrow('x', 80, 235, 345, 235, 'muted'), arrow('y', 195, 335, 195, 65, 'muted'),
    arrow('q', 195, 235, 195 + 105 * Math.cos(qa), 235 - 105 * Math.sin(qa), 'blue'), { ...arrow('k', 195, 235, 195 + 105 * Math.cos(ka), 235 - 105 * Math.sin(ka), 'green'), dashed: true } as E,
    text('qlabel', 385, 80, `Blue Q position: ${s === 2 ? 1 : 0}`, 'blue'), text('klabel', 385, 120, `Green K position: ${s}`, 'green'), matrix('qv', 405, 190, [s === 2 ? ['.707', '.707'] : [1, 0]], 'Rotated Q', 'blue', { cellW: 70 }), matrix('kv', 405, 280, [s === 0 ? [1, 0] : s === 1 ? ['.707', '.707'] : [0, 1]], 'Rotated K', 'green', { cellW: 70 }),
  ]);
}));

const sparse = lesson('causal-window-mask', 'A window changes the attention graph', 'The allowed cells shrink from a causal triangle to a diagonal band.', 'Six tokens; window W=2 includes the current token. The last step adds token 0 as a toy global key, not the bidirectional Longformer encoder pattern.', [0, 1, 2].map(s => step(
  ['Dense causal connections', 'Keep only the last two keys', 'Add a causal global-key shortcut'][s],
  ['Each row can read itself and every earlier column. Future columns are masked.', 'Only the diagonal and one cell to its left remain. This removes direct access to distant history.', 'The first column becomes available again. The added shortcut changes the graph and requires a compatible trained model.'][s],
  [matrix('mask', 115, 90, Array.from({ length: 6 }, (_, i) => Array.from({ length: 6 }, (_, j) => j <= i && (s === 0 || j >= i - 1 || s === 2 && j === 0) ? '✓' : '×')), 'Columns = key positions', 'green', { rowLabels: ['q0', 'q1', 'q2', 'q3', 'q4', 'q5'], columnLabels: ['0', '1', '2', '3', '4', '5'], highlight: Array.from({ length: 6 }, (_, i) => Array.from({ length: 6 }, (_, j): [number, number] => [i, j])).flat().filter(([i, j]) => j <= i && (s === 0 || j >= i - 1 || s === 2 && j === 0)) }), text('count', 430, 130, ['21 allowed cells', '11 allowed cells', '15 allowed cells'][s]), text('legend1', 430, 190, '✓ = visible key'), text('legend2', 430, 225, '× = masked key'), text('legend3', 105, 335, 'Rows = queries; no row may read a future column')]
)));

const cache = lesson('kv-cache-layer-append', 'Each layer owns its growing K and V', 'Old rows stay in place while each layer appends a new token row.', 'Two layers, one KV head, scalar K and V coordinates. Values are illustrative, not the result of a complete transformer. Previous queries are not retained in this KV cache.', [0, 1, 2].map(s => step(
  ['Prefill writes two rows per layer', 'Decode appends token 2', 'Token 2 queries its complete history'][s],
  ['Each layer has a separate cache because its keys and values come from that layer’s hidden states.', 'The new token contributes one K/V row at each layer; the earlier rows are reused rather than projected again.', 'Token 2’s query reads tokens 0, 1 and its own freshly appended row 2. Each layer uses its own cache to produce token 2’s attention output.'][s],
  [matrix('l0', 105, 95, s === 0 ? [[1, 2], [3, 1]] : [[1, 2], [3, 1], [2, 4]], 'Layer 0 cache', 'blue', { columnLabels: ['K', 'V'], rowLabels: s === 0 ? ['t0', 't1'] : ['t0', 't1', 't2'], highlight: s === 1 ? [[2, 0], [2, 1]] : [] }), matrix('l1', 375, 95, s === 0 ? [[2, 1], [1, 3]] : [[2, 1], [1, 3], [4, 2]], 'Layer 1 cache', 'purple', { columnLabels: ['K', 'V'], rowLabels: s === 0 ? ['t0', 't1'] : ['t0', 't1', 't2'], highlight: s === 1 ? [[2, 0], [2, 1]] : [] }),
    box('query0', 95, 270, 135, 42, s === 2 ? 'Token 2 Q: L0' : 'Token hidden', 'green'), box('query1', 365, 270, 135, 42, s === 2 ? 'Token 2 Q: L1' : 'Token hidden', 'green'), arrow('read0', 150, 266, 150, 210), arrow('read1', 420, 266, 420, 210), text('count', 70, 350, `Stored scalar entries: 2 layers × ${s === 0 ? 2 : 3} tokens × 2 (K and V)`)]
)));

const pages = lesson('kv-cache-paged-placement', 'Logical order survives scattered pages', 'A block table maps contiguous token history onto reusable physical slots.', 'One request, two tokens per block; each colored physical block stands for all required layer K/V payloads. Block numbers describe placement, not token positions.', [0, 1, 2].map(s => step(
  ['Map the first logical block', 'Grow into a nonadjacent block', 'Append without moving the old blocks'][s],
  ['Logical block 0 holds tokens 0–1 in physical slot 3.', 'Tokens 2–3 use slot 0. The block table restores sequence order when attention reads the history.', 'Token 4 starts a new block in slot 4. Slot 4 has one unused token position; existing blocks stay put.'][s],
  [matrix('table', 75, 85, s === 0 ? [[0, 3]] : s === 1 ? [[0, 3], [1, 0]] : [[0, 3], [1, 0], [2, 4]], 'Block table', 'purple', { columnLabels: ['logical', 'physical'], cellW: 80 }),
    ...Array.from({ length: 5 }, (_, i) => matrix(`page${i}`, 370, 63 + i * 54, [[i === 3 ? 't0' : i === 0 && s > 0 ? 't2' : i === 4 && s > 1 ? 't4' : '–', i === 3 ? 't1' : i === 0 && s > 0 ? 't3' : '–']], `slot ${i}`, i === 3 || i === 0 && s > 0 || i === 4 && s > 1 ? 'green' : 'muted', { cellW: 66, cellH: 29 })),
    arrow('map0', 240, 102, 355, 240), ...(s > 0 ? [arrow('map1', 240, 136, 355, 80)] : []), ...(s > 1 ? [arrow('map2', 240, 170, 355, 294)] : []), text('order', 65, 337, s === 0 ? 'Logical read order: t0 → t1' : s === 1 ? 'Logical read order: t0 → t1 → t2 → t3' : 'Logical read order: t0 → t1 → t2 → t3 → t4')]
)));

const routing = lesson('moe-token-routing', 'Dispatch tokens, then restore their order', 'Token rows move to selected experts and return to the original batch order.', 'Toy top-1 routing with three tokens, two experts and enough capacity. The gate is one-hot for clarity; practical gates, top-k weights and overflow policies vary.', [0, 1, 2].map(s => step(
  ['Choose one expert for each token', 'Group tokens on expert devices', 'Return outputs to token order'][s],
  ['Rows identify token A → E1, B → E0 and C → E1.', 'A and C move together to expert 1; B moves to expert 0. This permutation creates dispatch traffic.', 'Expert results move back to their original token positions so the next layer sees A, B, C in order.'][s],
  [{ id: 'e0', kind: 'path', d: 'M 280 65 H 440 V 165 H 280 Z', tone: 'blue' }, { id: 'e1', kind: 'path', d: 'M 485 65 H 645 V 240 H 485 Z', tone: 'purple' }, text('e0label', 305, 90, 'Expert 0', 'blue'), text('e1label', 510, 90, 'Expert 1', 'purple'),
    ...['A', 'B', 'C'].map((token, i) => matrix(`token${i}`, s === 1 ? i === 1 ? 300 : 505 : 75, s === 1 ? i === 2 ? 190 : 120 : 85 + i * 75, [[s === 2 ? `${token}′` : token]], '', i === 1 ? 'blue' : 'purple', { cellW: 65, cellH: 35 })),
    ...(s === 0 ? [arrow('a', 150, 101, 480, 132, 'purple'), arrow('b', 150, 176, 275, 132, 'blue'), arrow('c', 150, 251, 480, 207, 'purple')] : s === 2 ? [arrow('a', 480, 132, 150, 101, 'purple'), arrow('b', 275, 132, 150, 176, 'blue'), arrow('c', 480, 207, 150, 251, 'purple')] : []), matrix('gate', 290, 260, [[0, 1], [1, 0], [0, 1]], 'Routing', 'green', { cellH: 27, rowLabels: ['A', 'B', 'C'], columnLabels: ['E0', 'E1'] }), text('return', 465, 325, s === 2 ? 'Inverse permutation' : '3 tokens; 3 expert calls')]
)));

const parallel = lesson('parallelism-matrix-geometry', 'What exactly is split across devices?', 'Compare replicated matrices, tensor shards and consecutive layers.', 'Two devices and tiny 2×2 weights. Tensor split is by output rows using column-vector math; pipeline illustrates placement only, not a measured schedule. Expert placement appears in the routing walkthrough.', [0, 1, 2].map(s => step(
  ['Data parallel: copy weights, split examples', 'Tensor parallel: split one matrix', 'Pipeline parallel: split consecutive layers'][s],
  ['Both devices own W. Device 0 processes example A and device 1 processes B; training synchronizes parameter gradients.', 'Each device owns one output row of W and reads the same x. The two scalar results form one output vector.', 'Device 0 owns layer 0 and sends its activation to layer 1 on device 1. Multiple microbatches can fill the pipeline.'][s],
  [{ id: 'gpu0', kind: 'path', d: 'M 50 55 H 325 V 305 H 50 Z', tone: 'blue' }, { id: 'gpu1', kind: 'path', d: 'M 390 55 H 665 V 305 H 390 Z', tone: 'purple' }, text('gpu0label', 90, 85, 'Device 0', 'blue'), text('gpu1label', 430, 85, 'Device 1', 'purple'),
    matrix('w0', 90, 125, s === 1 ? [[1, 2]] : [[1, 2], [3, 4]], s === 2 ? 'Layer 0 weights' : s === 1 ? 'W row 0' : 'W replica', 'blue'), matrix('w1', 430, 125, s === 1 ? [[3, 4]] : s === 2 ? [[2, 0], [0, 2]] : [[1, 2], [3, 4]], s === 2 ? 'Layer 1 weights' : s === 1 ? 'W row 1' : 'W replica', 'purple'),
    text('in0', 85, 255, s === 0 ? 'example A' : s === 1 ? 'x=[1,1] → y₀=3' : 'x → hidden h'), text('in1', 425, 255, s === 0 ? 'example B' : s === 1 ? 'x=[1,1] → y₁=7' : 'hidden h → output'), arrow('link', 328, 220, 382, 220, 'green'), text('comm', 70, 345, ['Synchronize gradients across replicas during training', 'Collect output coordinates: y = [3,7]', 'Transfer hidden activations between layer stages'][s])]
)));

const quant = lesson('quantization-number-line', 'Round onto a finite number line', 'A real value moves to its nearest representable level, then reconstructs.', 'Toy symmetric signed quantizer: integer range −2…2, scale 0.5, zero point 0; nearest rounding and saturation. This five-level example is not a standard hardware bit format.', [0, 1, 2].map(s => step(
  ['Locate the floating-point value', 'Round to an integer code', 'Reconstruct and expose the error'][s],
  ['The weight 0.7 lies between representable values 0.5 and 1.0.', 'Divide by scale 0.5 to get 1.4; rounding selects integer code 1.', 'Multiply code 1 by 0.5 to reconstruct 0.5. Reconstruction error is −0.2.'][s],
  [arrow('axis', 90, 170, 640, 170, 'muted'), ...[-2, -1, 0, 1, 2].flatMap((v, i): E[] => [{ id: `tick${i}`, kind: 'path', d: `M ${120 + i * 120} 158 V 182`, tone: 'muted' }, text(`level${i}`, 100 + i * 120, 215, String(v * 0.5)), text(`code${i}`, 110 + i * 120, 250, String(v))]),
    { id: 'weight', kind: 'circle', x: s === 0 ? 528 : 480, y: 130, r: 13, filled: true, tone: 'amber' }, text('number', s === 0 ? 500 : 453, 95, s === 0 ? '0.7' : '0.5', 'amber'), text('units', 90, 295, 'Upper labels: reconstructed values; lower labels: integer codes'), text('calc', 90, 340, s === 0 ? 'Representable range: −1 to +1' : s === 1 ? 'q = round(0.7 / 0.5) = 1' : 'ŵ = 0.5 × 1 = 0.5;   ŵ − w = −0.2')]
)));

const groups = lesson('quantization-group-scales', 'One outlier can set everyone’s spacing', 'Split a small weight grid into groups with independent scales.', 'Toy signed codes −2…2, zero point 0, scale=max|w|/2. Round to nearest; rows become separate groups. Five integer levels illustrate granularity, not a standard bit format.', [0, 1, 2].map(s => step(
  ['One scale for the entire tensor', 'Split the rows into two groups', 'Reconstruct with each group’s scale'][s],
  ['The value 8 sets scale 4 for every entry. The small first-row values all round to zero.', 'The first row gets scale 0.5; the second keeps scale 4. More scale metadata buys finer first-row resolution.', 'Reconstruction preserves the first row exactly in this example. The second row still loses its value 2 under ties-to-even rounding.'][s],
  [matrix('w', 85, 95, [[0.5, 1], [2, 8]], 'Original W', 'blue', { cellW: 65 }), matrix('codes', 315, 95, s === 0 ? [[0, 0], [0, 2]] : [[1, 2], [0, 2]], 'Integer codes', 'purple', { cellW: 65 }), matrix('recon', 540, 95, s === 0 ? [[0, 0], [0, 8]] : [[0.5, 1], [0, 8]], 'Reconstruction', 'green', { cellW: 60, highlight: s === 2 ? [[0, 0], [0, 1], [1, 0], [1, 1]] : [] }), arrow('encode', 220, 128, 300, 128), arrow('decode', 449, 128, 525, 128),
    ...(s > 0 ? [{ id: 'group1', kind: 'path' as const, d: 'M 80 89 H 220 V 131 H 80 Z', tone: 'green' as const, width: 3 }, { id: 'group2', kind: 'path' as const, d: 'M 80 131 H 220 V 173 H 80 Z', tone: 'amber' as const, width: 3 }] : []), text('scale1', 100, 245, s === 0 ? 'One scale = 8 / 2 = 4' : 'Row 0 scale = 1 / 2 = 0.5'), text('scale2', 100, 285, s === 0 ? '0.5 / 4 and 1 / 4 both round to 0' : 'Row 1 scale = 8 / 2 = 4'), ...(s === 2 ? [matrix('storedscales', 500, 245, [[0.5], [4]], 'Stored scales', 'amber', { cellW: 85, rowLabels: ['g0', 'g1'] })] : []), text('meta', 100, 335, s === 0 ? 'Stored: 4 codes + 1 scale' : 'Stored: 4 codes + 2 scales')]
)));

const lora = lesson('lora-rank-one', 'A rank-one update is an outer product', 'Multiply a thin column and row, then add the result to frozen weights.', 'Toy W is 2×2, rank r=1, alpha/r=1. A=[1,−1], B=[2,3]ᵀ represent learned factors, not standard initialization. Small toy dimensions do not provide parameter savings.', [0, 1, 2, 3].map(s => step(
  ['Freeze the original matrix', 'Multiply the two thin factors', 'Add the rank-one update', 'Follow one input through both branches'][s],
  ['W remains fixed. Only the A and B factors are trainable.', 'Each row of BA is a scalar multiple of A, so its rank is at most one.', 'Add corresponding entries: 2+2=4, 0−2=−2, 0+3=3 and 1−3=−2. W+BA has rank two even though BA has rank one.', 'For x=[1,2], the base gives [2,2], A gives −1 and B gives [−2,−3]. Their sum is [0,−1].'][s],
  s === 3 ? [matrix('x', 55, 125, [[1], [2]], 'x'), matrix('baseout', 245, 80, [[2], [2]], 'Wx', 'blue'), matrix('ax', 245, 255, [[-1]], 'Ax', 'purple'), matrix('bax', 435, 255, [[-2], [-3]], 'B(Ax)', 'purple'), matrix('out', 595, 125, [[0], [-1]], 'Sum', 'green'), arrow('base', 105, 142, 230, 112), arrow('adapt', 105, 180, 230, 272), arrow('factor', 295, 272, 420, 272), arrow('sum0', 295, 112, 580, 142), arrow('sum1', 484, 272, 580, 190)] :
  [matrix('w', 70, 100, [[2, 0], [0, 1]], 'Frozen W', 'blue'), matrix('b', 270, 100, [[2], [3]], 'B: 2×1', 'purple'), matrix('a', 400, 100, [[1, -1]], 'A: 1×2', 'purple'), ...(s > 0 ? [matrix('ba', 270, 235, [[2, -2], [3, -3]], 'BA: rank ≤ 1', 'green'), arrow('outer', 420, 150, 370, 220)] : []), ...(s > 1 ? [matrix('effective', 535, 235, [[4, -2], [3, -2]], 'W + BA', 'green'), arrow('add', 365, 270, 520, 270)] : []), text('train', 55, 345, s === 0 ? 'Frozen: 4 weights; trainable: 2 + 2 factor entries' : 'Low rank constrains the update; it does not constrain W')]
)));

const qlora = lesson('qlora-storage-compute', 'Low-bit storage feeds higher-precision math', 'Stored codes expand for arithmetic while the adapter remains trainable.', 'Schematic weight block; c0/c1 stand for NF4 codes plus scale, not literal weights. BF16 is the illustrated compute and adapter dtype. Adapter scaling alpha/r=1; output is Ŵx+B(Ax).', [0, 1, 2].map(s => step(
  ['Keep the frozen base in compact storage', 'Decode a block for arithmetic', 'Update the adapter, not the base codes'][s],
  ['The frozen weight block stores low-bit codes and scale metadata. A and B are separate higher-precision tensors.', 'Decode the frozen block for Ŵx. In parallel, the same input passes through A then B to form B(Ax). Add the two branch outputs.', 'Gradients flow through both computations to earlier layers, while optimizer updates change A and B only. The frozen base codes remain unchanged.'][s],
  [matrix('codes', 40, 75, [['c0', 'c1']], 'Frozen 4-bit codes', 'blue', { cellW: 55 }), matrix('scale', 40, 150, [['scale']], 'Metadata', 'muted', { cellW: 100 }),
    matrix('a', 210, 255, [[s === 0 ? 'A' : 'Ax']], 'BF16 factor A', 'purple', { cellW: 95 }), matrix('b', 390, 255, [[s === 0 ? 'B' : 'B(Ax)']], 'BF16 factor B', 'purple', { cellW: 105 }),
    ...(s > 0 ? [matrix('decoded', 255, 75, [['ŵ0', 'ŵ1']], 'BF16 base Ŵ', 'green', { cellW: 60 }), arrow('decode', 155, 92, 245, 92), box('baseout', 450, 78, 100, 50, 'Ŵx', 'green'), arrow('basecompute', 380, 92, 445, 92), box('input', 55, 250, 55, 42, 'x', 'blue'), arrow('into-a', 115, 272, 200, 272, 'purple'), arrow('into-b', 310, 272, 380, 272, 'purple'), { id: 'input-base', kind: 'path' as const, d: 'M 80 246 V 200 H 420 V 115 H 445', tone: 'blue' as const },
      arrow('basepath', 555, 105, 605, 190), arrow('adpath', 500, 272, 605, 230, 'purple'), { id: 'sum', kind: 'circle' as const, x: 615, y: 210, r: 22, label: '+', tone: 'green' as const }, arrow('output', 640, 210, 682, 210), text('outlabel', 660, 185, 'y', 'green') ] : []),
    ...(s === 2 ? [arrow('grad', 490, 315, 250, 315, 'amber'), text('gradtext', 60, 350, 'Optimizer updates A and B; frozen codes stay fixed', 'amber')] : [text('storage', 45, 340, 'Storage precision and compute precision are separate choices')])]
)));

export const architectureVisuals: VisualLesson[] = [heads, flash, rope, sparse, cache, pages, routing, parallel, quant, groups, lora, qlora];
