import { useState } from 'react';
import { useMutation,useQuery } from '@tanstack/react-query';
import { Link,useParams } from '@tanstack/react-router';
import { ArrowRight,ArrowUpRight,Bookmark,Check,ChevronDown,Clock,Layers,RotateCcw } from 'lucide-react';
import { api,refreshStudy,type ArticleResponse } from './api';
import { articleOrder,categories } from '../shared/catalog';
import { CodeBlock,ErrorBox,Loading,Markdown } from './common';
import { Diagram } from './Diagram';
export function ArticlePage(){const {slug}=useParams({strict:false});return <ArticleContent key={slug} slug={slug!}/>;}
function ArticleContent({slug}:{slug:string}){
  const [tab,setTab]=useState<'article'|'cards'>('article');
  const article=useQuery({queryKey:['article',slug],queryFn:()=>api<ArticleResponse>(`/articles/${slug}`)});
  const progress=useMutation({mutationFn:(body:{isRead?:boolean;bookmarked?:boolean})=>api(`/articles/${slug}/progress`,body,'PATCH'),onSuccess:()=>refreshStudy()});
  const enroll=useMutation({mutationFn:()=>api(`/articles/${slug}/enroll`,{}),onSuccess:()=>refreshStudy()});
  if(article.isPending)return <Loading/>;if(article.error)return <ErrorBox error={article.error} retry={()=>article.refetch()}/>;
  const {article:a,progress:p,cards}=article.data;const category=categories.find(c=>c.slug===a.category);let fig=0;const next=articleOrder[articleOrder.indexOf(slug)+1];
  return <div className="page article-page"><Link to="/category/$slug" params={{slug:a.category}} className="back-link">← {category?.title}</Link><header className="article-header"><div className="article-kicker"><span className="eyebrow" style={{color:category?.color}}>{a.difficulty.toUpperCase()} / FIELDNOTE {String(articleOrder.indexOf(slug)+1).padStart(2,'0')}</span><button className={`icon-button bookmark-button ${p.bookmarked?'saved':''}`} aria-label={p.bookmarked?'Remove bookmark':'Bookmark article'} disabled={progress.isPending} onClick={()=>progress.mutate({bookmarked:!p.bookmarked})}><Bookmark size={20} fill={p.bookmarked?'currentColor':'none'}/></button></div><h1>{a.title}</h1><p className="article-deck">{a.summary}</p><div className="article-metadata"><span><Clock size={15}/>{a.minutes} min read</span><span><Layers size={15}/>{a.sections.filter(s=>s.diagram).length} diagrams</span><span>{cards.length} recall cards</span>{p.isRead&&<span className="read-badge"><Check size={14}/>Explored</span>}</div></header>
    <div className="article-tabs"><button className={tab==='article'?'active':''} onClick={()=>setTab('article')}>The fieldnote</button><button className={tab==='cards'?'active':''} onClick={()=>setTab('cards')}>Recall deck <span>{cards.length}</span></button></div>
    {a.category==='ai-farm'&&<div className="bundle-note"><div><strong>The companion example</strong><p>Docker Compose, Nginx, Express, PostgreSQL, and a minimal chat client. Follow the guide and replace the operator settings before running.</p></div><a className="button secondary" href="/examples/ai-farm.zip" download>Download the example <ArrowUpRight size={16}/></a></div>}
    {(progress.error||enroll.error)&&<ErrorBox error={progress.error??enroll.error}/>}
    {tab==='article'?<div className="reading-layout"><div className="article-body"><div className="objectives"><span className="eyebrow">WHAT YOU’LL WALK AWAY WITH</span><ul>{a.learningObjectives.map(x=><li key={x}><Check size={16}/><Markdown>{x}</Markdown></li>)}</ul>{a.prerequisites.length>0&&<div className="prerequisites">Connects to {a.prerequisites.map(x=><Link key={x} to="/lesson/$slug" params={{slug:x}}>{x.split('-').join(' ')}<ArrowUpRight size={12}/></Link>)}</div>}</div>
      {a.sections.map((section,index)=><section className="article-section" id={section.id} key={section.id}><div className="section-heading"><span>{String(index+1).padStart(2,'0')}</span><h2>{section.title.replace(/^\d+[.)]\s*/, '')}</h2></div>{section.paragraphs.map((p,i)=><Markdown key={i}>{p}</Markdown>)}{section.formula&&<div className="formula"><span>THE RELATIONSHIP</span><pre>{section.formula}</pre></div>}{section.bullets&&<ul className="article-bullets">{section.bullets.map((b,i)=><li key={i}><Markdown>{b}</Markdown></li>)}</ul>}{section.code&&<CodeBlock {...section.code}/ >}{section.diagram&&<Diagram diagram={section.diagram} index={++fig}/>}</section>)}
      <section id="interview" className="interview-box"><span className="eyebrow">AT THE WHITEBOARD</span><h2>{a.interview.question}</h2><details><summary>Think it through, then compare your answer <ChevronDown size={17}/></summary><Markdown>{a.interview.answer}</Markdown><h3>Go one level deeper</h3><ul>{a.interview.followUps.map(x=><li key={x}>{x}</li>)}</ul></details></section>
      <section id="pitfalls" className="article-section"><h2>Where answers go wrong</h2><ul className="pitfalls">{a.pitfalls.map(x=><li key={x}><Markdown>{x}</Markdown></li>)}</ul><h3>Before you move on</h3><ul className="checklist">{a.checklist.map(x=><li key={x}><Check size={16}/><Markdown>{x}</Markdown></li>)}</ul></section>
      <section id="sources" className="sources"><span className="eyebrow">FOLLOW THE EVIDENCE</span><h2>Sources & further reading</h2><p>Verified against primary sources during authoring. Examples are educational; benchmark assumptions and execution limits are stated in the text.</p>{a.sources.map((s,i)=><a key={s.url} href={s.url} target="_blank" rel="noreferrer"><span>{String(i+1).padStart(2,'0')}</span><div><strong>{s.title}<ArrowUpRight size={14}/></strong><p>{s.note}</p></div></a>)}</section>
      <div className="finish-article"><div><span className="eyebrow">LET THE IDEA SETTLE</span><h2>Read it. Recall it. Keep it.</h2><p>Reading and deck enrollment are separate. Add the deck when you’re ready to practice.</p></div><div className="button-row"><button className={`button ${p.isRead?'secondary':'primary'}`} disabled={progress.isPending} onClick={()=>progress.mutate({isRead:!p.isRead})}><Check size={16}/>{p.isRead?'Mark as unread':'Mark as explored'}</button>{p.enrolledAt?<Link className="button secondary" to="/review" search={{deck:slug}}><RotateCcw size={16}/>Review this deck</Link>:<button className="button secondary" disabled={enroll.isPending} onClick={()=>enroll.mutate()}><Layers size={16}/>{enroll.isPending?'Adding…':'Add recall deck'}</button>}</div></div>{next&&<Link to="/lesson/$slug" params={{slug:next}} className="next-article">Continue to the next fieldnote <ArrowRight size={20}/></Link>}
      </div><aside className="article-outline"><span className="eyebrow">IN THIS FIELDNOTE</span>{a.sections.map((s,i)=><a key={s.id} href={`#${s.id}`}><span>{String(i+1).padStart(2,'0')}</span>{s.title.replace(/^\d+[.)]\s*/, '')}</a>)}<a href="#interview">↗ At the whiteboard</a><a href="#sources">↗ Sources & evidence</a><div className="outline-note"><Layers size={21}/><strong>Make the ideas stick.</strong><p>{cards.length} prompts to test the mechanisms and tradeoffs.</p><button className="text-button" onClick={()=>setTab('cards')}>Preview the deck <ArrowRight size={14}/></button></div></aside></div>:<div className="deck-preview"><div className="deck-banner"><div><span className="eyebrow">ACTIVE RECALL</span><h2>Explain it without the notes.</h2><p>Each prompt asks you to retrieve an idea, not recognize an answer.</p></div>{p.enrolledAt?<Link to="/review" search={{deck:slug}} className="button primary">Review this deck<ArrowRight size={16}/></Link>:<button className="button primary" disabled={enroll.isPending} onClick={()=>enroll.mutate()}>{enroll.isPending?'Adding…':`Add ${cards.length} cards to review`}<Layers size={16}/></button>}</div>{cards.map((card,i)=><details key={card.id} className="preview-card"><summary><span>{String(i+1).padStart(2,'0')}</span><strong>{card.front}</strong><ChevronDown size={18}/></summary><div><Markdown>{card.back}</Markdown>{card.state&&<p className="card-state">{card.state.attempts} scheduled attempts · {card.state.practice} practice · {card.state.attempts?`Next review ${new Date(card.state.due).toLocaleDateString()}`:'New card'}</p>}</div></details>)}</div>}
  </div>;
}
