import { Slider as UISlider } from '@/components/ui/slider';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { useId,useState } from 'react';
import { Link } from '@tanstack/react-router';
import { ArrowUpRight,FlaskConical,RotateCcw } from 'lucide-react';
import { Diagram } from './Diagram';
export function Lab(){const [batch,setBatch]=useState(4);const [tokens,setTokens]=useState(8192);const [heads,setHeads]=useState(8);const [bytes,setBytes]=useState(2);const [rate,setRate]=useState(.2);const [step,setStep]=useState(0);const [context,setContext]=useState(4096);const [output,setOutput]=useState(512);const [arrival,setArrival]=useState(2);
  const gib=2*32*batch*tokens*heads*128*bytes/2**30;const sequence=Array.from({length:13},(_,i)=>{const w=4*(1-2*rate)**i;return [i,w*w] as [number,number];});const w=4*(1-2*rate)**step;
  return <div className="page lab-page"><header className="page-heading compact"><div><span className="eyebrow">THE CONCEPT LAB</span><h1>Change a variable.<br/><em>Follow the consequence.</em></h1><p>Three small experiments to make the tradeoffs tangible.</p></div><FlaskConical size={80} className="page-emblem"/></header><section className="lab-section"><div className="lab-intro"><span className="eyebrow">01 / MEMORY IS A BUDGET</span><h2>The KV cache calculator</h2><p>A hypothetical 32-layer transformer with head dimension 128. Change concurrency, context, KV heads, or precision to see the raw cache footprint.</p><Button asChild variant="link" className="h-auto justify-start px-0 whitespace-normal"><Link to="/lesson/$slug" params={{slug:'serving-kv-cache'}}>Read the systems explanation<ArrowUpRight size={15}/></Link></Button><div className="lab-controls"><Slider label="Concurrent sequences" value={batch} min={1} max={32} onChange={setBatch}/><Slider label="Cached tokens per sequence" value={tokens} min={512} max={32768} step={512} onChange={setTokens}/><LabSelect label="KV heads" value={heads} onChange={setHeads} options={[[1,'1 · MQA'],[8,'8 · GQA'],[32,'32 · MHA']]}/><LabSelect label="Bytes per cached value" value={bytes} onChange={setBytes} options={[[1,'1 · nominal 8-bit'],[2,'2 · FP16 / BF16'],[4,'4 · FP32']]}/></div></div><Card className="lab-result gap-0 shadow-none"><span className="eyebrow">RAW KV STORAGE</span><strong>{gib.toFixed(2)}<small>GiB</small></strong><p>2 × 32 layers × {batch} sequences × {tokens.toLocaleString()} tokens × {heads} KV heads × 128 × {bytes} bytes</p><Diagram index={1} diagram={{kind:'bars',title:'The head-sharing effect',caption:'Calculated raw KV memory in GiB with the same layers, context, concurrency, head dimension, and precision. Query head count remains 32.',nodes:[{label:'MHA · 32 KV heads',value:+(gib*32/heads).toFixed(2),detail:'Distinct K and V for each query head.'},{label:'GQA · 8 KV heads',value:+(gib*8/heads).toFixed(2),detail:'Groups of query heads share K and V.'},{label:'MQA · 1 KV head',value:+(gib/heads).toFixed(2),detail:'All query heads share one K and V pair.'}]}}/><p className="lab-caveat">Excludes model weights, activations, workspace, allocator overhead, quantization metadata, and fragmentation. A supported cache precision and enough total VRAM are still required.</p></Card></section>
    <section className="lab-section"><div className="lab-intro"><span className="eyebrow">02 / FOLLOW THE GRADIENT</span><h2>Learning rate, made visible</h2><p>Minimize L(w) = w², starting at w = 4. The gradient is 2w. Every step applies w ← w − η·2w. This simple convex loss lets you see overshoot and divergence directly.</p><Slider label="Learning rate η" value={rate} min={.05} max={1.1} step={.05} onChange={n=>{setRate(n);setStep(0);}}/><div className="gradient-values"><span>Step <b>{step}</b></span><span>w <b>{w.toFixed(4)}</b></span><span>Loss <b>{(w*w).toFixed(4)}</b></span></div><div className="button-row"><Button onClick={()=>setStep(s=>Math.min(12,s+1))} disabled={step>=12}>Take a gradient step</Button><Button variant="ghost" size="icon" onClick={()=>setStep(0)} aria-label="Reset gradient steps"><RotateCcw size={19}/></Button></div><p className="lab-caveat">0 &lt; η &lt; 1 converges for this function. η = 1 oscillates without improvement. η &gt; 1 diverges. Real neural-network losses do not share this simple guarantee.</p></div><Card className="lab-result gap-0 shadow-none"><Diagram index={2} diagram={{kind:'curve',title:'Loss over optimizer steps',caption:'Exact calculated trajectory for L(w)=w². The light gray curve shows all 12 steps; the blue points show your current progress.',xLabel:'Optimizer step',yLabel:'Loss = w²',series:[{name:'Full trajectory',points:sequence},{name:'Your steps',points:sequence.slice(0,Math.max(1,step+1))}]}}/></Card></section>
    <section className="lab-section"><div className="lab-intro"><span className="eyebrow">03 / KNOW YOUR WORKLOAD</span><h2>Translate requests into tokens</h2><p>Request count alone hides the work. Estimate separate prompt and generated token rates before selecting servers or deciding a latency target.</p><Slider label="Requests per second" value={arrival} min={1} max={20} onChange={setArrival}/><Slider label="Average input tokens" value={context} min={256} max={16384} step={256} onChange={setContext}/><Slider label="Average generated tokens" value={output} min={64} max={2048} step={64} onChange={setOutput}/></div><Card className="lab-result capacity-result gap-0 shadow-none"><span className="eyebrow">OFFERED WORKLOAD</span><strong>{(arrival*context).toLocaleString()}<small>input tok/s</small></strong><strong>{(arrival*output).toLocaleString()}<small>output tok/s</small></strong><p>At an illustrative 10-second mean residence time, Little’s law gives <b>{arrival*10} in-flight requests</b> in a stable system.</p><p className="lab-caveat">These are workload calculations, not hardware benchmarks. Prefill and decode contend for resources. Measure throughput at the required p95 latency and reserve capacity for bursts and failures.</p><Button asChild variant="link" className="h-auto justify-start px-0 whitespace-normal"><Link to="/lesson/$slug" params={{slug:'interview-design'}}>Put the estimates into a design<ArrowUpRight size={15}/></Link></Button></Card></section></div>;
}
function Slider({label,value,min,max,step=1,onChange}:{label:string;value:number;min:number;max:number;step?:number;onChange:(n:number)=>void}){const labelId=useId();return <div className="slider-label grid gap-3"><div className="flex items-center justify-between gap-3"><Label id={labelId}>{label}</Label><output>{Number(value.toFixed(2)).toLocaleString()}</output></div><UISlider aria-labelledby={labelId} min={min} max={max} step={step} value={[value]} onValueChange={values=>onChange(values[0])}/></div>;}
function LabSelect({label,value,onChange,options}:{label:string;value:number;onChange:(n:number)=>void;options:[number,string][]}){const id=useId();return <div className="grid gap-2"><Label htmlFor={id}>{label}</Label><Select value={String(value)} onValueChange={next=>onChange(Number(next))}><SelectTrigger id={id} className="w-full"><SelectValue/></SelectTrigger><SelectContent>{options.map(([key,text])=><SelectItem key={key} value={String(key)}>{text}</SelectItem>)}</SelectContent></Select></div>;}
