import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link,useParams } from '@tanstack/react-router';
import { ArrowRight, ArrowUpRight, BookOpen, Bookmark, Check, Clock, Search, SlidersHorizontal, Sparkles } from 'lucide-react';
import { api,type Catalog,type CatalogArticle,type Stats } from './api';
import { Empty,ErrorBox,Icon,Loading,percent } from './common';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
export function Learn(){
  const {slug}=useParams({strict:false});const [search,setSearch]=useState('');const [filter,setFilter]=useState('all');
  const catalog=useQuery({queryKey:['catalog'],queryFn:()=>api<Catalog>('/catalog')});const stats=useQuery({queryKey:['stats'],queryFn:()=>api<Stats>('/stats')});
  if(catalog.isPending)return <Loading/>;if(catalog.error)return <ErrorBox error={catalog.error} retry={()=>catalog.refetch()}/>;
  const {articles,categories}=catalog.data;const category=categories.find(c=>c.slug===slug);
  const visible=articles.filter(a=>(!slug||a.category===slug)&&(!search||`${a.title} ${a.summary} ${categories.find(c=>c.slug===a.category)?.title}`.toLowerCase().includes(search.toLowerCase()))&&(filter!=='saved'||a.bookmarked)&&(filter!=='unread'||!a.isRead)&&(filter!=='enrolled'||a.enrolledAt));
  const next=articles.find(a=>!a.isRead)??articles[0];
  return <div className="page learn-page"><header className="page-heading"><div><span className="eyebrow">{category?'EXPLORE A DISCIPLINE':'THE LEARNING PATH'}</span><h1>{category?category.title:<>Build intuition.<br/><em>Then go deeper.</em></>}</h1><p>{category?category.description:'A practical field guide to modern AI, built for senior-level thinking.'}</p></div><div className="heading-mark" aria-hidden="true"><div/><div/><div/><span>λ</span></div></header>
    {!slug&&<><div className="overview-strip"><div><strong>{articles.length}</strong><span>in-depth articles</span></div><div><strong>{articles.reduce((s,a)=>s+a.diagramCount,0)}</strong><span>visual explanations</span></div><div><strong>{articles.reduce((s,a)=>s+a.cardCount,0)}</strong><span>recall prompts</span></div><div className="reading-meter"><div><strong>{stats.data?.read??0}<small> / {articles.length}</small></strong><span>articles explored</span></div><Progress className="mini-meter" value={percent(stats.data?.read??0,articles.length)} aria-label="Articles explored"/></div></div>
    <div className="feature-grid"><Link to="/lesson/$slug" params={{slug:next?.slug??'transformer-foundations'}} className="min-w-0 h-full"><Card className="continue-card h-full gap-0 shadow-none"><span className="eyebrow"><span className="status-dot"/>{stats.data?.read?'KEEP YOUR MOMENTUM':'START WITH THE MECHANISM'}</span><h2>{next?.title??'Your learning path is being prepared'}</h2><p>{next?.summary}</p><div className="feature-bottom"><span><Clock size={14}/>{next?.minutes??15} min read</span><span className="round-arrow"><ArrowRight size={20}/></span></div></Card></Link><Link to="/category/$slug" params={{slug:'ai-farm'}} className="min-w-0 h-full"><Card className="farm-card block h-full gap-0 shadow-none"><div className="farm-graphic" aria-hidden="true"><span/><i/><span/><i/><span/></div><span className="eyebrow">THE PRACTICAL SERIES</span><h2>Your own<br/>corporate AI farm.</h2><p>Two servers. One coherent system.<br/>Build the mental model, layer by layer.</p><span className="text-link">Explore the walkthrough <ArrowUpRight size={17}/></span></Card></Link></div></>}
    {category&&<Button asChild variant="link" className="back-link h-auto p-0"><Link to="/">← All disciplines</Link></Button>}
    <div className="catalog-toolbar"><div><h2>{category?'Inside this discipline':'Explore the field'}</h2><span>{category?`${visible.length} articles`:`${categories.length} disciplines. One connected picture.`}</span></div><label className="search"><Search size={17}/><Input type="search" className="h-auto shadow-none focus-visible:ring-0" aria-label="Search articles" placeholder="Search concepts, topics…" value={search} onChange={e=>setSearch(e.target.value)}/><kbd>/</kbd></label></div>
    <div className="filters"><ToggleGroup type="single" value={filter} onValueChange={value=>{if(value)setFilter(value);}} aria-label="Filter articles" className="gap-[3px] sm:gap-[7px]">{[['all','All articles'],['unread','To explore'],['saved','Saved'],['enrolled','My decks']].map(([key,label])=><ToggleGroupItem key={key} value={key} className={filter===key?'selected h-auto':'h-auto'}>{key==='saved'?<Bookmark size={14}/>:key==='enrolled'?<SlidersHorizontal size={14}/>:null}{label}</ToggleGroupItem>)}</ToggleGroup><span aria-live="polite">{visible.length} articles</span></div>
    {visible.length===0&&<Empty title="No articles found">Try another search or filter. Save an article using its bookmark button.</Empty>}
    <div className="discipline-list">{categories.filter(c=>visible.some(a=>a.category===c.slug)).map((c)=><section className="discipline" key={c.slug}><div className="discipline-heading"><div className="category-icon"><Icon name={c.icon}/></div><div><Link to="/category/$slug" params={{slug:c.slug}}><h3>{c.title}</h3></Link><p>{c.description}</p></div><span className="discipline-count">{articles.filter(a=>a.category===c.slug&&a.isRead).length}/{articles.filter(a=>a.category===c.slug).length}<Check size={13}/></span></div><div className="article-grid">{visible.filter(a=>a.category===c.slug).map(a=><ArticleCard key={a.slug} article={a}/>)}</div></section>)}</div><footer className="page-footer"><Sparkles size={15}/>Learn a mechanism. Explain a tradeoff. Remember it tomorrow.</footer></div>;
}
function ArticleCard({article:a}:{article:CatalogArticle}){return <Link to="/lesson/$slug" params={{slug:a.slug}} className="min-w-0 h-full"><Card className="article-card h-full gap-0 shadow-none"><div className="card-meta"><span className="article-index">{String(a.position+1).padStart(2,'0')}</span><Badge variant="outline" className="difficulty">{a.difficulty}</Badge><span className="card-status">{a.bookmarked&&<Bookmark size={14} fill="currentColor"/>}{a.isRead&&<Check size={15}/>}</span></div><h4>{a.title}</h4><p>{a.summary}</p><div className="card-bottom"><span><Clock size={13}/>{a.minutes} min</span><span><BookOpen size={13}/>{a.cardCount} cards</span><ArrowUpRight size={17}/></div></Card></Link>;}
