import { useEffect,useRef,useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Link,useSearch } from '@tanstack/react-router';
import { ArrowRight,Check,Layers,RotateCcw,Sparkles } from 'lucide-react';
import { api,ApiError,refreshStudy,type Catalog,type ReviewCard,type Stats } from './api';
import type { Schedule } from '../server/scheduler';
import { Empty,ErrorBox,Markdown,percent } from './common';
const grades=['Blank','Forgot','Almost','Hard','Good','Easy'];
type Submission={cardId:number;quality:number;version:number;requestId:string;responseMs:number;kind:'scheduled'|'practice'};
export function Review(){const search=useSearch({strict:false}) as {deck?:string};return <ReviewSession key={search.deck??'all'} deck={search.deck}/>;}
function ReviewSession({deck}:{deck?:string}){
  const [queue,setQueue]=useState<ReviewCard[]>([]);const [started,setStarted]=useState(false);const [revealed,setRevealed]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<unknown>(null);const [newLimit,setNewLimit]=useState(10);const [counts,setCounts]=useState({scheduled:0,correct:0,practice:0});
  const pending=useRef<Submission|null>(null);const opened=useRef(Date.now());const inFlight=useRef(false);
  const stats=useQuery({queryKey:['stats'],queryFn:()=>api<Stats>('/stats')});const catalog=useQuery({queryKey:['catalog'],queryFn:()=>api<Catalog>('/catalog')});
  const card=queue[0];const selected=catalog.data?.articles.find(a=>a.slug===deck);const eligible=deck?selected?.enrolledAt:catalog.data?.articles.some(a=>a.enrolledAt);
  async function start(){setBusy(true);setError(null);try{const result=await api<{cards:ReviewCard[]}>(`/review?newLimit=${newLimit}${deck?`&deck=${encodeURIComponent(deck)}`:''}`);setQueue(result.cards);setStarted(true);setRevealed(false);setCounts({scheduled:0,correct:0,practice:0});pending.current=null;opened.current=Date.now();}catch(e){setError(e);}finally{setBusy(false);}}
  async function grade(quality:number){if(!card||inFlight.current||!revealed)return;inFlight.current=true;setBusy(true);setError(null);
    const submission=pending.current??{cardId:card.id,quality,version:card.state.version,requestId:crypto.randomUUID(),responseMs:Math.min(86400000,Math.max(0,Date.now()-opened.current)),kind:card.kind};pending.current=submission;
    try{const result=await api<{state:Schedule}>('/reviews',submission);const actual=submission.quality;setCounts(c=>({scheduled:c.scheduled+Number(card.kind==='scheduled'),correct:c.correct+Number(card.kind==='scheduled'&&actual>=3),practice:c.practice+Number(card.kind==='practice')}));setQueue(q=>{const rest=q.slice(1);if(actual<4)rest.push({...card,state:result.state,kind:'practice',previews:card.previews.map(()=>result.state.interval)});return rest;});pending.current=null;setRevealed(false);opened.current=Date.now();await refreshStudy();}catch(e){setError(e);}finally{setBusy(false);inFlight.current=false;}}
  useEffect(()=>{const handle=(e:KeyboardEvent)=>{const t=e.target as HTMLElement;if(e.repeat||e.ctrlKey||e.metaKey||e.altKey||t.closest('input,textarea,select,button,a,summary,[contenteditable="true"]')||busy||error)return;if(e.code==='Space'&&card){e.preventDefault();setRevealed(true);}else if(revealed&&/^[0-5]$/.test(e.key)){e.preventDefault();void grade(Number(e.key));}};window.addEventListener('keydown',handle);return()=>window.removeEventListener('keydown',handle);});
  return <div className="page review-page"><header className="page-heading compact"><div><span className="eyebrow">SPACED REPETITION</span><h1>A little recall.<br/><em>A longer memory.</em></h1><p>{selected?selected.title:'Retrieve the idea before you revisit the answer.'}</p></div><RotateCcw className="page-emblem" size={80}/></header>
    {!!error&&<ErrorBox error={error} retry={pending.current&&!(error instanceof ApiError&&error.status===409)?()=>grade(pending.current!.quality):()=>{pending.current=null;void start();}}/>}
    {!started?<><div className="review-start"><div className="review-counts"><div><strong>{deck?selected?.due??0:stats.data?.due??0}</strong><span>cards due now</span></div><div><strong>{deck?selected?.fresh??0:stats.data?.fresh??0}</strong><span>new cards available</span></div></div><div className="review-setup"><h2>Make room for what you know.</h2><p>Due cards come first. New cards follow. Difficult answers return for a little extra practice.</p><label>New cards this session<select value={newLimit} onChange={e=>setNewLimit(Number(e.target.value))}>{[0,5,10,20,50].map(n=><option key={n} value={n}>{n===0?'Due cards only':`${n} new cards`}</option>)}</select></label><button className="button primary" disabled={busy||!eligible} onClick={start}>{busy?'Preparing…':'Begin a review'}<ArrowRight size={18}/></button><small>Up to 100 due cards per session. Grades save immediately.</small></div></div>{!eligible&&<Empty title="Your first deck is waiting">Open any fieldnote and choose “Add recall deck” to get started. <Link to="/">Explore the learning path →</Link></Empty>}<div className="review-method"><div><Layers/><h3>Read for understanding</h3><p>Build a model of the mechanism before testing it.</p></div><div><RotateCcw/><h3>Recall before revealing</h3><p>Say your answer aloud. Notice where it gets vague.</p></div><div><Sparkles/><h3>Grade the recall honestly</h3><p>The schedule adapts to your answer, not your ambition.</p></div></div></>:
      card?<div className="review-active"><div className="review-session-bar"><span>{card.kind==='practice'?'REINFORCEMENT':'SCHEDULED RECALL'}</span><span>{queue.length} remaining · {counts.scheduled+counts.practice} answered</span></div><div className="flashcard"><Link to="/lesson/$slug" params={{slug:card.articleSlug}} className="eyebrow">{card.articleTitle}</Link><h2>{card.front}</h2>{revealed?<div className="flashcard-answer"><span className="eyebrow">THE REASONING</span><Markdown>{card.back}</Markdown></div>:<button className="button primary reveal" onClick={()=>setRevealed(true)}>Reveal the answer <span>Space</span></button>}</div>{revealed&&<div className="grade-area"><p>{card.kind==='practice'?'Practice reinforces recall without changing your next due date.':'How well did you retrieve the answer?'}</p><div className="grade-buttons">{grades.map((g,i)=><button key={g} className={`grade grade-${i}`} disabled={busy||!!pending.current} onClick={()=>grade(i)}><kbd>{i}</kbd><strong>{g}</strong><small>{card.kind==='practice'?'Practice':`${card.previews[i]} ${card.previews[i]===1?'day':'days'}`}</small></button>)}</div><small>0–2 = missed · 3–5 = recalled · grades below 4 return for practice</small></div>}<button className="text-button session-end" disabled={busy||!!pending.current} onClick={()=>{setQueue([]);}}>Finish this session</button></div>:
      <div className="session-complete"><span className="completion-icon"><Check size={32}/></span><span className="eyebrow">A LITTLE STRONGER THAN BEFORE</span><h2>{counts.scheduled+counts.practice?'Good work. Let it settle.':'You’re all caught up.'}</h2><p>{counts.scheduled+counts.practice?'Your answers are saved. Your next reviews are scheduled.':'No eligible cards with these settings. You can add new decks or include more new cards.'}</p><div className="session-summary"><div><strong>{counts.scheduled}</strong><span>scheduled answers</span></div><div><strong>{counts.scheduled?`${percent(counts.correct,counts.scheduled)}%`:'—'}</strong><span>recall accuracy</span></div><div><strong>{counts.practice}</strong><span>practice answers</span></div></div><div className="button-row"><Link to="/" className="button primary">Back to the field<ArrowRight size={17}/></Link><button className="button secondary" onClick={()=>setStarted(false)}>Review settings</button></div></div>}
  </div>;
}
