import { useState } from 'react';
import { useMutation,useQuery } from '@tanstack/react-query';
import { Link,Outlet,useRouterState } from '@tanstack/react-router';
import { BookOpen, ChartNoAxesCombined, CircleHelp, FlaskConical, LogOut, Menu, RotateCcw, ArrowUpRight, X } from 'lucide-react';
import { api,ApiError,queryClient,type User,type Stats } from './api';
import { categories } from '../shared/catalog';
import { ErrorBox,Icon,Loading } from './common';
import { useTheme } from './ThemeContext';
export function Shell(){
  const { theme } = useTheme();
  const me=useQuery({queryKey:['me'],queryFn:()=>api<User>('/me'),retry:false});
  const [open,setOpen]=useState(false);
  const location=useRouterState({select:s=>s.location.pathname});
  if(me.isPending)return <Loading/>;
  if(me.error){if(me.error instanceof ApiError && me.error.status===401)return <Login/>;return <div className="standalone"><ErrorBox error={me.error} retry={()=>me.refetch()}/></div>;}
  return <div className="app-shell"><a className="skip-link" href="#main">Skip to content</a><div className="mobile-header"><Link to="/" className="brand"><Logo/>latent<span>fieldnotes</span></Link><button className="icon-button" aria-label={open?'Close navigation':'Open navigation'} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<button className="nav-scrim" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}
    <aside className={`sidebar ${open?'open':''}`}><Link to="/" className="brand" onClick={()=>setOpen(false)}><Logo/>latent<span>fieldnotes</span></Link><div className="workspace-label"><span className="status-dot"/>PERSONAL WORKSPACE</div><nav aria-label="Main navigation" onClick={()=>setOpen(false)}><Link to="/" className={location==='/'||location.startsWith('/category')||location.startsWith('/lesson')?'nav-item active':'nav-item'}><BookOpen size={19}/>Learning path</Link><Link to="/review" search={{deck:undefined}} className="nav-item" activeProps={{className:'nav-item active'}}><RotateCcw size={19}/>Spaced repetition<DueCount/></Link><Link to="/progress" className="nav-item" activeProps={{className:'nav-item active'}}><ChartNoAxesCombined size={19}/>Your progress</Link><Link to="/lab" className="nav-item" activeProps={{className:'nav-item active'}}><FlaskConical size={19}/>Concept lab</Link><div className="nav-label">EXPLORE THE FIELD</div>{categories.map(c=><Link key={c.slug} to="/category/$slug" params={{slug:c.slug}} className="topic-link"><span style={{background:theme.colors[`category-${c.slug}`]}}/>{c.title}</Link>)}</nav><div className="sidebar-bottom"><Link to="/guide" className="nav-item" onClick={()=>setOpen(false)}><CircleHelp size={18}/>How to study here<ArrowUpRight size={15}/></Link><div className="user-row"><div className="avatar">{me.data?.username[0]?.toUpperCase()}</div><div><strong>{me.data?.username}</strong><small>Keep your curiosity.</small></div><button className="icon-button" aria-label="Sign out" onClick={async()=>{await api('/logout',{});queryClient.clear();locationReload();}}><LogOut size={17}/></button></div></div></aside>
    <main id="main" className="main"><div className="topbar"><span>AI SYSTEMS / <strong>{location==='/review'?'RECALL':location==='/progress'?'PROGRESS':location==='/lab'?'EXPERIMENTS':'THE FIELD GUIDE'}</strong></span><span className="topbar-note"><span className="status-dot"/> Built for deeper understanding</span></div><Outlet/></main></div>;
}
function locationReload(){window.location.reload();}
function DueCount(){const s=useQuery({queryKey:['stats'],queryFn:()=>api<Stats>('/stats')});return s.data?.due?<span className="nav-count">{s.data.due}</span>:null;}
export function Logo(){return <span className="logo"><span/><i/></span>;}
function Login(){const [username,setUsername]=useState('Admin');const [password,setPassword]=useState('');const login=useMutation({mutationFn:()=>api<User>('/login',{username,password}),onSuccess:user=>{queryClient.setQueryData(['me'],user);}});return <div className="login-page"><div className="login-art"><div className="brand"><Logo/>latent<span>fieldnotes</span></div><div><span className="eyebrow">UNDERSTAND THE SYSTEM. NOT JUST THE ANSWER.</span><h1>Small notes.<br/>Deep understanding.</h1><p>A field guide to the ideas behind modern AI.<br/>From the first gradient to the last token.</p><div className="login-network" aria-hidden="true">{[0,1,2,3,4].map(i=><div key={i} style={{transform:`translateY(${Math.sin(i)*25}px)`}}>{[0,1,2].map(j=><i key={j} style={{opacity:.35+(i+j)%3*.2}}/>)}</div>)}</div></div><span className="login-footer">ARCHITECTURE · THEORY · SYSTEMS · PRACTICE</span></div><div className="login-form"><span className="eyebrow">YOUR PERSONAL LEARNING SPACE</span><h2>Welcome back.</h2><p>Pick up a concept. Make it stick.</p><form onSubmit={e=>{e.preventDefault();login.mutate();}}><label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" placeholder="Enter your password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{login.error&&<ErrorBox error={login.error}/>}<button className="button primary" disabled={login.isPending}>{login.isPending?'Signing in…':'Open your fieldnotes'}<ArrowUpRight size={18}/></button></form><p className="login-caption">Read carefully. Recall honestly. Connect the ideas.</p></div></div>;}
